### ISSUE TITLE
Tests are fails under Windows with MinGW

### ISSUE THREAD

**Issue by nxrighthere** [ARM-software/progress64#7]
It seems that many tests are fails under Windows with MinGW (lfring/msqueue/ringbuf/etc). Programs are terminating earlier than expected for some reason (a message with success is not reached). Do you observe such a problem on your machine?

**Comment by WonderfulVoid** [comment]
I did som quick testing when doing the initial Windows support and cross compiling using MinGW. From what I remember it all worked back then (excluding the benchmarks which require pthreads).
I will re-test.

**Comment by WonderfulVoid** [comment]
Using mingw-w64 with GCC 8.1.0 on Windows 10. I see a call to p64_hazptr_unregister() which calls p64_mfree() which calls free which calls memset -> SIGTRAP.

**Comment by WonderfulVoid** [comment]
The problem is that memory allocated using _aligned_malloc() must be freed using _aligned_free(). It cannot be freed using the normal free() call. This isn't documented on the man page
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-malloc?view=vs-2019
and there is even a remark "_aligned_malloc is based on malloc".
However the code example on the same page uses _aligned_free() instead of standard free().

The solution is to **always** use _aligned_malloc() and _aligned_free() on Windows, don't mix with calls to malloc() and free().

**Comment by nxrighthere** [comment]
Maybe just use a portable `_mm_malloc(size, alignment)` w/ `_mm_free(pointer)`?

**Comment by WonderfulVoid** [comment]
_mm_malloc/_mm_free are documented as Intel functions. Will they be available on Windows on Arm?

**Comment by nxrighthere** [comment]
Yes, they should be available there.

**Comment by nxrighthere** [comment]
I see some compilers like MSVC are wrapping platform-specific API using these functions as macros.

**Comment by nxrighthere** [comment]
Fixed with https://github.com/ARM-software/progress64/commit/a8336802f464dbcda27af15344688010507f86a5.

**Comment by WonderfulVoid** [comment]
Sorry it took such time.

**Comment by nxrighthere** [comment]
I've fixed it locally before the commit. 😉

**Comment by WonderfulVoid** [comment]
The idea with os_abstraction.c is also that a user should be able to override the default implementation. Perhaps I should better document the calls in os_abstraction.h.
